name: "Hackathon Video Generator"
team: "Team Scripting Quarantino"
language: "es"
objective: "save time in hackathons by automatically generating the video for the hackathon project"
objective_keyword: "time"
steps: 
  step_one: "It reads in a config file that contains all information relevant to your project"
  step_two: "It automatically generates the audio and the slides you need for your video"
  step_three: "Your beautiful video is ready to be shown to the world"
technologies: 
  tech_one: "A distance sensor"
  tech_two: "A luminosity sensor"
  tech_three: "A Shiny application"
organizer: "Hacklarious" 
