name: "Our Random Project"
team: "A really cool team"
language: "it"
objective: "To demonstrate how to generate a video"
objective_keyword: "demo"
steps: 
  step_one: "We did something really important"
  step_two: "And a few other things"
  step_three: "And now the demo is ready"
organizer: "Hacklarious" 
